set_property PACKAGE_PIN D4 [get_ports {clk}]
set_property IOSTANDARD LVCMOS33 [get_ports {clk}]
 
set_property PACKAGE_PIN  B4 [get_ports {PWN}]
set_property IOSTANDARD LVCMOS33 [get_ports {PWN}]
set_property  PACKAGE_PIN  B5 [get_ports {cmos_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_data[0]}]
set_property  PACKAGE_PIN  B6 [get_ports {cmos_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_data[2]}]
set_property  PACKAGE_PIN  A7 [get_ports {cmos_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_data[4]}]
set_property  PACKAGE_PIN  E5 [get_ports {cmos_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_data[6]}]
set_property  PACKAGE_PIN  D8 [get_ports {cmos_sdat}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_sdat}]
set_property PULLUP TRUE [get_ports cmos_sdat]
set_property  PACKAGE_PIN  D6 [get_ports {cmos_xclk}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_xclk}]
set_property  PACKAGE_PIN  E6 [get_ports {cmos_href}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_href}]
set_property  PACKAGE_PIN  A4 [get_ports {rst}]
set_property IOSTANDARD LVCMOS33 [get_ports {rst}]

set_property  PACKAGE_PIN  C6 [get_ports {cmos_pclk}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_pclk}]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {cmos_pclk}]

set_property  PACKAGE_PIN  C7 [get_ports {cmos_vsync}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_vsync}]
set_property  PACKAGE_PIN  D9 [get_ports {cmos_sclk}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_sclk}]
 
set_property  PACKAGE_PIN  A5 [get_ports {cmos_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_data[1]}]
set_property  PACKAGE_PIN  B7 [get_ports {cmos_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_data[3]}]
set_property  PACKAGE_PIN  C4 [get_ports {cmos_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_data[5]}]
set_property  PACKAGE_PIN  D5 [get_ports {cmos_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_data[7]}]

  set_property PACKAGE_PIN F5 [get_ports {vgaRed[0]}]				
  set_property IOSTANDARD LVCMOS33 [get_ports {vgaRed[0]}]
  set_property PACKAGE_PIN F4 [get_ports {vgaRed[1]}]                
  set_property IOSTANDARD LVCMOS33 [get_ports {vgaRed[1]}]
  set_property PACKAGE_PIN M16 [get_ports {vgaRed[2]}]                
  set_property IOSTANDARD LVCMOS33 [get_ports {vgaRed[2]}]
  set_property PACKAGE_PIN M15 [get_ports {vgaRed[3]}]                
  set_property IOSTANDARD LVCMOS33 [get_ports {vgaRed[3]}]
  set_property PACKAGE_PIN R16 [get_ports {vgaBlue[0]}]                
  set_property IOSTANDARD LVCMOS33 [get_ports {vgaBlue[0]}]
  set_property PACKAGE_PIN T15 [get_ports {vgaBlue[1]}]                
  set_property IOSTANDARD LVCMOS33 [get_ports {vgaBlue[1]}]
  set_property PACKAGE_PIN P14 [get_ports {vgaBlue[2]}]                
  set_property IOSTANDARD LVCMOS33 [get_ports {vgaBlue[2]}]
  set_property PACKAGE_PIN T14 [get_ports {vgaBlue[3]}]                
  set_property IOSTANDARD LVCMOS33 [get_ports {vgaBlue[3]}]
  set_property PACKAGE_PIN N16 [get_ports {vgaGreen[0]}]                
  set_property IOSTANDARD LVCMOS33 [get_ports {vgaGreen[0]}]
  set_property PACKAGE_PIN P15 [get_ports {vgaGreen[1]}]                
  set_property IOSTANDARD LVCMOS33 [get_ports {vgaGreen[1]}]
  set_property PACKAGE_PIN P16 [get_ports {vgaGreen[2]}]                
  set_property IOSTANDARD LVCMOS33 [get_ports {vgaGreen[2]}]
  set_property PACKAGE_PIN R15 [get_ports {vgaGreen[3]}]                
  set_property IOSTANDARD LVCMOS33 [get_ports {vgaGreen[3]}]
  set_property PACKAGE_PIN R13 [get_ports {Hsync}]                        
  set_property IOSTANDARD LVCMOS33 [get_ports {Hsync}]
  set_property PACKAGE_PIN T13 [get_ports {Vsync}]                        
  set_property IOSTANDARD LVCMOS33 [get_ports {Vsync}]
  
  set_property PACKAGE_PIN E3 [get_ports {LED[11]}]                        
  set_property IOSTANDARD LVCMOS33 [get_ports {LED[11]}]
  set_property PACKAGE_PIN H3 [get_ports {LED[10]}]                        
  set_property IOSTANDARD LVCMOS33 [get_ports {LED[10]}]
  set_property PACKAGE_PIN G5 [get_ports {LED[9]}]                        
  set_property IOSTANDARD LVCMOS33 [get_ports {LED[9]}]
  set_property PACKAGE_PIN R1 [get_ports {LED[8]}]                        
  set_property IOSTANDARD LVCMOS33 [get_ports {LED[8]}]
  set_property PACKAGE_PIN T2 [get_ports {LED[7]}]                        
  set_property IOSTANDARD LVCMOS33 [get_ports {LED[7]}]
  set_property PACKAGE_PIN T3 [get_ports {LED[6]}]                        
  set_property IOSTANDARD LVCMOS33 [get_ports {LED[6]}]
  set_property PACKAGE_PIN T4 [get_ports {LED[5]}]                        
  set_property IOSTANDARD LVCMOS33 [get_ports {LED[5]}]
  set_property PACKAGE_PIN N6 [get_ports {LED[4]}]                        
  set_property IOSTANDARD LVCMOS33 [get_ports {LED[4]}]
  set_property PACKAGE_PIN T5 [get_ports {LED[3]}]                        
  set_property IOSTANDARD LVCMOS33 [get_ports {LED[3]}]
  set_property PACKAGE_PIN R7 [get_ports {LED[2]}]                        
  set_property IOSTANDARD LVCMOS33 [get_ports {LED[2]}]
  set_property PACKAGE_PIN R8 [get_ports {LED[1]}]                        
  set_property IOSTANDARD LVCMOS33 [get_ports {LED[1]}]
  set_property PACKAGE_PIN P9 [get_ports {LED[0]}]                        
  set_property IOSTANDARD LVCMOS33 [get_ports {LED[0]}]
  
  
  ##Buttons
  set_property PACKAGE_PIN K3 [get_ports {row[0]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {row[0]}]
  set_property PACKAGE_PIN M6 [get_ports {row[1]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {row[1]}]
  set_property PACKAGE_PIN P10 [get_ports {row[2]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {row[2]}]
  set_property PACKAGE_PIN R10 [get_ports {row[3]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {row[3]}]
  
  
  set_property PACKAGE_PIN R12 [get_ports {btn[0]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {btn[0]}]
  set_property PACKAGE_PIN T12 [get_ports {btn[1]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {btn[1]}]
  set_property PACKAGE_PIN R11 [get_ports {btn[2]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {btn[2]}]
  set_property PACKAGE_PIN T10 [get_ports {btn[3]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {btn[3]}]
  
  set_property PULLDOWN true [get_ports {btn[3]}]
  set_property PULLDOWN true [get_ports {btn[2]}]
  set_property PULLDOWN true [get_ports {btn[1]}]
  set_property PULLDOWN true [get_ports {btn[0]}]
  
  set_property PACKAGE_PIN F3 [get_ports {en}]
  set_property IOSTANDARD LVCMOS33 [get_ports {en}]
  set_property PACKAGE_PIN H4 [get_ports {flag_down}]
  set_property IOSTANDARD LVCMOS33 [get_ports {flag_down}]
  set_property PACKAGE_PIN N4 [get_ports {sel}]
  set_property IOSTANDARD LVCMOS33 [get_ports {sel}]
  set_property PACKAGE_PIN R2 [get_ports {standard[8]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {standard[8]}]
  set_property PACKAGE_PIN R3 [get_ports {standard[7]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {standard[7]}]
  set_property PACKAGE_PIN P4 [get_ports {standard[6]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {standard[6]}]
  set_property PACKAGE_PIN R5 [get_ports {standard[5]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {standard[5]}]
  set_property PACKAGE_PIN P6 [get_ports {standard[4]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {standard[4]}]
  set_property PACKAGE_PIN R6 [get_ports {standard[3]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {standard[3]}]
  set_property PACKAGE_PIN T7 [get_ports {standard[2]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {standard[2]}]
  set_property PACKAGE_PIN T8 [get_ports {standard[1]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {standard[1]}]
  set_property PACKAGE_PIN T9 [get_ports {standard[0]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {standard[0]}]
  
  
  #seg
  set_property PACKAGE_PIN P11 [get_ports {seg[0]}]
  set_property PACKAGE_PIN N12 [get_ports {seg[1]}]
  set_property PACKAGE_PIN L14 [get_ports {seg[2]}]
  set_property PACKAGE_PIN K13 [get_ports {seg[3]}]
  set_property PACKAGE_PIN K12 [get_ports {seg[4]}]
  set_property PACKAGE_PIN P13 [get_ports {seg[5]}]
  set_property PACKAGE_PIN M14 [get_ports {seg[6]}]
  set_property PACKAGE_PIN L13 [get_ports {seg[7]}]
  #bit_code
  set_property PACKAGE_PIN N11 [get_ports {bit_code[5]}]
  set_property PACKAGE_PIN N14 [get_ports {bit_code[4]}]
  set_property PACKAGE_PIN N13 [get_ports {bit_code[3]}]
  set_property PACKAGE_PIN M12 [get_ports {bit_code[2]}]
  set_property PACKAGE_PIN H13 [get_ports {bit_code[1]}]
  set_property PACKAGE_PIN G12 [get_ports {bit_code[0]}]
  
  #seg
  set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {seg[7]}]
  #bit_code
  set_property IOSTANDARD LVCMOS33 [get_ports {bit_code[0]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {bit_code[1]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {bit_code[2]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {bit_code[3]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {bit_code[4]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {bit_code[5]}]