# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tftg256-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/ASUS/Desktop/p_SYSTEM/p_SYSTEM.cache/wt [current_project]
set_property parent.project_path C:/Users/ASUS/Desktop/p_SYSTEM/p_SYSTEM.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/ASUS/Desktop/p_SYSTEM/p_SYSTEM.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/ASUS/Desktop/p_SYSTEM/MENU.coe
add_files {{C:/Users/ASUS/Desktop/p_SYSTEM/vga_bram 2.0.coe}}
read_verilog -library xil_defaultlib {
  C:/Users/ASUS/Desktop/p_SYSTEM/p_SYSTEM.srcs/sources_1/new/XADC.v
  C:/Users/ASUS/Desktop/p_SYSTEM/p_SYSTEM.srcs/sources_1/new/data_pro.v
  C:/Users/ASUS/Desktop/p_SYSTEM/p_SYSTEM.srcs/sources_1/new/div_clk.v
  C:/Users/ASUS/Desktop/p_SYSTEM/p_SYSTEM.srcs/sources_1/new/mux_vga.v
  C:/Users/ASUS/Desktop/p_SYSTEM/p_SYSTEM.srcs/sources_1/new/pro_vga.v
  C:/Users/ASUS/Desktop/p_SYSTEM/p_SYSTEM.srcs/sources_1/new/seg.v
  C:/Users/ASUS/Desktop/p_SYSTEM/p_SYSTEM.srcs/sources_1/new/type1_disp.v
  C:/Users/ASUS/Desktop/p_SYSTEM/p_SYSTEM.srcs/sources_1/new/type1_vga.v
  C:/Users/ASUS/Desktop/p_SYSTEM/p_SYSTEM.srcs/sources_1/new/type2_vga.v
  C:/Users/ASUS/Desktop/p_SYSTEM/p_SYSTEM.srcs/sources_1/new/type3_vga.v
  C:/Users/ASUS/Desktop/p_SYSTEM/p_SYSTEM.srcs/sources_1/new/uart_rx.v
  C:/Users/ASUS/Desktop/p_SYSTEM/p_SYSTEM.srcs/sources_1/new/vga_disp.v
  C:/Users/ASUS/Desktop/p_SYSTEM/p_SYSTEM.srcs/sources_1/new/vga_menu.v
  C:/Users/ASUS/Desktop/p_SYSTEM/p_SYSTEM.srcs/sources_1/new/vga_part.v
  C:/Users/ASUS/Desktop/p_SYSTEM/p_SYSTEM.srcs/sources_1/new/system.v
}
read_ip -quiet C:/Users/ASUS/Desktop/p_SYSTEM/p_SYSTEM.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/ASUS/Desktop/p_SYSTEM/p_SYSTEM.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ASUS/Desktop/p_SYSTEM/p_SYSTEM.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xdc]

read_ip -quiet C:/Users/ASUS/Desktop/p_SYSTEM/p_SYSTEM.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all c:/Users/ASUS/Desktop/p_SYSTEM/p_SYSTEM.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

read_ip -quiet C:/Users/ASUS/Desktop/p_SYSTEM/p_SYSTEM.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/ASUS/Desktop/p_SYSTEM/p_SYSTEM.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ASUS/Desktop/p_SYSTEM/p_SYSTEM.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ASUS/Desktop/p_SYSTEM/p_SYSTEM.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet C:/Users/ASUS/Desktop/p_SYSTEM/p_SYSTEM.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci
set_property used_in_implementation false [get_files -all c:/Users/ASUS/Desktop/p_SYSTEM/p_SYSTEM.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/ASUS/Desktop/p_SYSTEM/p_SYSTEM.srcs/constrs_1/new/cons.xdc
set_property used_in_implementation false [get_files C:/Users/ASUS/Desktop/p_SYSTEM/p_SYSTEM.srcs/constrs_1/new/cons.xdc]


synth_design -top system -part xc7a35tftg256-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef system.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file system_utilization_synth.rpt -pb system_utilization_synth.pb"
